language: java

# addons:
#   apt:
#     packages:
#     - imagemagick   
#     - ghostscript
#     - rvm


# before_install:
#  - ./setup-env.sh

jdk:
 - oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository/
  - $HOME/.rvm 

script:
- ./setup-env.sh
- ./onramp.sh

env:
- SPRING_PROFILES_ACTIVE=ci

