language: java

before_install:
- cp .travis.settings.xml $HOME/.m2/settings.xml

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository/
  - $HOME/.rvm
  - $HOME/.bundle
  - $HOME/bin/kindlegen/

script:
- mvn -e verify deploy
- ci/render-book.sh

env:
- SPRING_PROFILES_ACTIVE=ci
